sudo: required

services:
  - docker

env:
  global:
    - appUser="consul"
    - appGroup="10000"

install:
  - docker build --rm --no-cache -t cryptout/consul ../consul

script:
  - ./rundocker.sh
  - sleep 10
  - bats tests/

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push cryptout/consul:latest;
    fi

notifications:
  email: false
